android {
    sourceSets {
        main.java {
            srcDirs += 'src/main/kotlin'
        }
    }
}
dependencies {
    implementation "androidx.work:work-runtime-ktx:2.9.0"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1"
    implementation "com.google.code.gson:gson:2.8.9"
    implementation "androidx.sqlite:sqlite-ktx:2.3.1"
}
